#pragma once
// UART line receiver + executor for STM32 HAL.
// Usage:
// 1) Call STM32A_Init(&huartX); it will start IT receive (1 byte).
// 2) In your HAL_UART_RxCpltCallback, call STM32A_RxCpltCallback(huart);
// 3) Implement/override Motor_* functions to link with your motor control logic.
//
// This module parses ASCII lines using proto.c and calls Motor_* accordingly.

#include "proto.h"
#include "usart.h" // generated by CubeMX, adjust include path as needed
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

void STM32A_Init(UART_HandleTypeDef *uart);
void STM32A_RxCpltCallback(UART_HandleTypeDef *huart);

// Weak motor hooks (override these in your project)
void Motor_Stop(void);
void Move_OpenLoop_cm(int dist_cm, int speed_0_255);        // +cm forward, -cm backward if preferred
void Turn_OpenLoop_deg(int angle_deg, int speed_0_255, int left);

#ifdef __cplusplus
}
#endif


